spring.application.name=3Line-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/modern_api
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=vanguard-super-secret-key-32-chars-long-minimal-change-in-prod
jwt.expiration=86400000
